### ISSUE TITLE
uninitialized constant CouchRestRails::Document::COUCHDB_SERVER

### ISSUE THREAD

**Issue by uhgall** [henrypoydar/couchrest-rails#1]
First of all, nice work! I was frustrated with BasicModel and decided to write something better, and then saw you had already done it. 

One problem: I get the error above, pretty much no matter what I try to do.
See below for details.

ALso get this when trying to run a unit test.

---

linux-3:mma uhgall$ rake couchdb:create --trace
(in /Users/uhgall/code/mma)
*\* Invoke couchdb:create (first_time)
*\* Invoke environment (first_time)
*\* Execute environment
rake aborted!
uninitialized constant CouchRestRails::Document::COUCHDB_SERVER
/Users/uhgall/code/mma/vendor/rails/activesupport/lib/active_support/dependencies.rb:105:in `const_missing'
/Users/uhgall/code/mma/vendor/plugins/couchrest-rails/lib/couch_rest_rails/document.rb:3
/Users/uhgall/code/mma/vendor/rails/activesupport/lib/active_support/dependencies.rb:380:in`load_without_new_constant_marking'
/Users/uhgall/code/mma/vendor/rails/activesupport/lib/active_support/dependencies.rb:380:in `load_file'
/Users/uhgall/code/mma/vendor/rails/activesupport/lib/active_support/dependencies.rb:521:in`new_constants_in'
/Users/uhgall/code/mma/vendor/rails/activesupport/lib/active_support/dependencies.rb:379:in `load_file'
/Users/uhgall/code/mma/vendor/rails/activesupport/lib/active_support/dependencies.rb:259:in`require_or_load'
/Users/uhgall/code/mma/vendor/rails/activesupport/lib/active_support/dependencies.rb:425:in `load_missing_constant'
/Users/uhgall/code/mma/vendor/rails/activesupport/lib/active_support/dependencies.rb:80:in`const_missing'
/Users/uhgall/code/mma/vendor/plugins/basic_model/lib/basic_model.rb:34
/Library/Ruby/Site/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
/Library/Ruby/Site/1.8/rubygems/custom_require.rb:31:in`require'

**Comment by henrypoydar** [comment]
Can you try again with the latest version?  It has been significantly refactored. Thanks!
