### ISSUE TITLE
hard coded dependency on 'couchrest' gem

### ISSUE THREAD

**Issue by grempe** [henrypoydar/couchrest-rails#3]
The plugin has a hard coded dependency on the 'couchrest' gem in the plugin init:

http://github.com/hpoydar/couchrest-rails/blob/master/init.rb

This is problematic for those of us using one of the many seemingly official forks of couchrest in our app (e.g. jchris-couchrest, mattetti-couchrest, couchrest-couchrest, or just plain couchrest from rubyforge).  According to mattettit 'couchrest-couchrest' is the official repo, but building gems from that repo on github seems to be borked.

Instead of hardcoding the specific gem I would instead specify that users need to specify one of these in their environment.rb with the :lib param of 'couchrest'.  I am currently using (working ok so far in my very initial usage) the mattetti-couchrest gem in my app.  In order to do this I needed to override your init.rb and specify:

```
config.gem 'mattetti-couchrest', :lib => 'couchrest'
```

instead of specifying config.gem statements in your plugin, I would try to require 'couchrest', (and the same for the other gems you hardcode) and raise an exception if one is missing.  And add to the docs the requirement that the user has provided each of the approprtiate config gem statements in their environment.rb which will be much more flexible for users.

**Comment by henrypoydar** [comment]
Good catch.  Fixed: http://github.com/hpoydar/couchrest-rails/commit/b83e00d76d8d1827c7bfc6d76c2ff4ba587c7e09

**Comment by grempe** [comment]
Excellent.  Thanks!
