### ISSUE TITLE
line in init.rb causes shoulda/test-unit tests to fail badly

### ISSUE THREAD

**Issue by grempe** [henrypoydar/couchrest-rails#4]
I had to comment out the following line in the plugin:

http://github.com/hpoydar/couchrest-rails/blob/master/init.rb#L2

The inclusion of the spec/rails/matchers caused my apps tests to fail badly in a very non-obvious way (required a session with git bisect to resolve the root cause).

I am not sure why is this seemingly test related code is being included in the normal runtime anyway?  Shouldn't this only be included when running the plugin tests?  There should be no assumptions about rspec being present or in use for apps that pull this plugin in.

Thanks.

**Comment by henrypoydar** [comment]
Fixed

**Comment by grempe** [comment]
Thanks.  I really appreciate how responsive you have been to my bug reports over the last few days.  I am under the gun to build something that works with your plugin right now so your fixes are making my life (and the plugin I hope) better while not requiring me to maintain my own fork!

**Comment by henrypoydar** [comment]
No problem ... thanks for all of the great big catches.  Good luck with the project!
