### ISSUE TITLE
there are no CouchRestRails::Document models using {Database}

### ISSUE THREAD

**Issue by shenoudab** [henrypoydar/couchrest-rails#5]
Dears i got that Warning while creating the database.
while i have a model using CouchRestRails::Document

class Post < CouchRestRails::Document
  use_database :couchtry

  property  :title
  property  :body

  timestamps!

  view_by :title

  validates_presence_of :title
end

please advise,

Thanks.

**Comment by henrypoydar** [comment]
This was resolved in a recent commit.  Please make sure you have the very latest version. Thanks
